default:
  # Rutas promedio que puede atender 1 veh?culo por tipolog?a
  factor_ruta:
    factor_r_bus: 1.5
    factor_r_buseta: 2.5
    factor_r_microbus: 1.5
    factor_r_van: 1
    factor_r_camioneta: 2.5

  # Consumos en kWh/Km
  factor_consumo:
    BUS: 1.1
    BUSETA: 0.7
    MICROBUS: 0.5
    VAN: 1.0
    CAMIONETA: 0.1

  modif_consumo:
    perdidas: 0.2

  modif_km_vacio:
    km_vacio_gral: 7
    km_vacio_perc: 0.26
    
  meta_pcbe:
    beneficiarios: 13147
    
  emisiones:
    BUS: 
      CO: 1.555
      VOC: 0.091
      NOX: 9.603
      SOX: 0.014
      PM25: 0.108
      PM10: 0.154
      CO2EQ: 858.1
    BUSETA:
      CO: 0.992
      VOC: 0.057
      NOX: 5.775
      SOX: 0.010
      PM25: 0.075
      PM10: 0.110
      CO2EQ: 571.6
    MICROBUS:
      CO: 0.309
      VOC: 0.057
      NOX: 2.327
      SOX: 0.004
      PM25: 0.034
      PM10: 0.034
      CO2EQ: 339.7
    CAMIONETA:
      CO: 0.820
      VOC: 0.127 
      NOX: 0.309
      SOX: 0.013
      PM25: 0.009
      PM10: 0.011
      CO2EQ: 274.0
    VAN:
      CO: 0.309
      VOC: 0.057
      NOX: 2.327
      SOX: 0.004
      PM25: 0.034
      PM10: 0.034
      CO2EQ: 339.7
  factor_exp:
    semana_esco: 40
    semana_gral: 52
  
    
      
      
      
  
    