default:
  # Rutas promedio que puede atender 1 veh?culo por tipolog?a
  factor_ruta:
    factor_r_bus: 1.5
    factor_r_buseta: 2.5
    factor_r_microbus: 1.5
    factor_r_van: 1
    factor_r_camioneta: 2.5

  # Consumos en kWh/Km
  factor_consumo:
    BUS: 1.1
    BUSETA: 0.7
    MICROBUS: 0.5
    VAN: 1.0
    CAMIONETA: 0.1

  modif_consumo:
    perdidas: 0.2

  modif_km_vacio:
    km_vacio_gral: 7
    km_vacio_perc: 0.26
    
  meta_pcbe:
    beneficiarios: 13147